### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by nimit2801** [ChromaTechFR/ProgressBar#1]
I wanted to use this package, but there were no specific use cases or examples on the repo.
It would really help someone to add this thing to their project.

Thank You

**Comment by ChromaTechFR** [comment]
> I wanted to use this package, but there were no specific use cases or examples on the repo.
> It would really help someone to add this thing to their project.
> 
> Thank You

If you want I’ll explain you later, let me your discord and I’ll help you. 
( I’ll update the readme thanks )

**Comment by nimit2801** [comment]
> 
> 
> > I wanted to use this package, but there were no specific use cases or examples on the repo.
> > It would really help someone to add this thing to their project.
> > Thank You
> 
> If you want I’ll explain you later, let me your discord and I’ll help you.
> ( I’ll update the readme thanks )

Discord: Nimit#4979
Thanks for considering the issue!

**Comment by ChromaTechFR** [comment]
> > > I wanted to use this package, but there were no specific use cases or examples on the repo.
> > > It would really help someone to add this thing to their project.
> > > Thank You
> > 
> > 
> > If you want I’ll explain you later, let me your discord and I’ll help you.
> > ( I’ll update the readme thanks )
> 
> Discord: Nimit#4979
> Thanks for considering the issue!

https://github.com/ChromaTechFR/ProgressBar#readme done. =)
